# Generated by Django 5.2.5 on 2025-09-07 15:54

import django.db.models.deletion
import halthcare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(default='male', max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('hospital', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(default='male', max_length=50)),
                ('medical_history', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_id', models.CharField(default=halthcare.models.genrate_map_id, max_length=50, unique=True)),
                ('remarks', models.CharField(max_length=300)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halthcare.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halthcare.patient')),
            ],
        ),
    ]
