# Generated by Django 5.2.5 on 2025-09-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
    ]
